title: League Curriculum
cname: curriculum.jointheleague.org
description: League Curriculum Links and Documentation
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  repo: 'jointheleague-it/league-curriculum'
  docRepo: 'jointheleague-it/league-curriculum'
  docsDir: 'docs/src'
  editLinkText: ''
  #editLinks: true
  lastUpdated: false
  logo: /assets/Flag.png
  nav:
  - link: /docs/
    text: Docs
  - link: https://jointheleague.org
    text: The LEAGUE
  sidebar:
  - title: The Lesson Builder
    collapsable: false
    children:
      - path: /lb/quickstart.md
        title: Quickstart
      - path: /lb/how_it_works.md
        title: How it Works
      - path: /lb/sources.md
        title: Finding Lessons  
  - title: Java
    collapsable: false
    path: /java/
    children:
      - title: Java Levels and Modules
        path: /java/java_levels.md
      - title: Java Dev Container Quickstart
        path: /java/devcontainer.md
      - title: Using Module Repositories
        path: /java/module_repos.md
